export const kissing = "&#x1F618;"; //kissing face
export const person = "&#128145;"; //person with heart
export const wifi = "&#128147;"; //little wifi (shake?)
export const broken = "&#128148;"; //broken  :(
export const with_small = "&#128149;"; //with small
export const sparkles = "&#128150;"; //with sparkles
export const echo = "&#128151;"; //echo heart
export const with_arrow = "&#128152;"; //with arrow
export const blue = "&#128153;"; //blue
export const green = "&#128154;"; //green
export const yellow = "&#128155;"; //yellow
export const purple = "&#128156;"; //purple
export const with_bow = "&#128157;"; //with bow
export const multiple = "&#128158;"; //multiple
export const in_pink_box = "&#128159;"; //in pink box
export const red = "&#10084;&#65039;"; //red heart
export const dead = "&#128538;";
export const none = "&nbsp;";

export const i_kissing = "throwing_kiss"; // ???
export const i_person = "kissing"; // ?????
export const i_wifi = "heart_beating";
export const i_broken = "heart_broken";
export const i_with_small = "heart_with_small";
export const i_sparkles = "heart_sparkles";
export const i_echo = "heart_echo";
export const i_with_arrow = "heart_arrow";
export const i_blue = "heart_blue";
export const i_green = "heart_green";
export const i_yellow = "heart_yellow";
export const i_purple = "heart_purple";
export const i_with_bow = "heart_bow";
export const i_multiple = "heart_multiple";
export const i_in_pink_box = "heart_in_box";
export const i_red = "heart_red";
export const i_dead = "kissing"; //? ????? ??
export const i_none = "transparent";
